version: "3"
services:
  nginx_test:
    build:
      context: ..
      dockerfile: front/Dockerfile
    environment: 
      SERVICE_HOST: back_test
    ports:
      - 80:80
    depends_on:
      - back_test
  back_test:
    build:
      context: ..
      dockerfile: back/Dockerfile
    environment: 
      DATABASE_HOST: database_test
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - database_test
    volumes:
      - ../back/:/code
  database_test:
    image: mariadb
    restart: always
    environment:
      MARIADB_USER: clikodrome
      MARIADB_PASSWORD: clikodrome
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: Clikodrome
    volumes:
      - ../back/db/:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"